backend:
  name: git-gateway
  branch: beta

media_folder: "static/assets"

collections:
  - label: Pages
    name: pages
    files:
      - file: ./src/data/commercial-flights.md
        name: commercial-flights
        label: Commercial Flights
        fields:
          - name: splashImg
            label: splash img
            widget: image
          - name: title
            label: title
            widget: string
          - name: description
            label: description
            widget: markdown
          - name: caseStudies
            label: case studies
            widget: list
            fields:
              - name: title
                label: title
                widget: string
              - name: shortTitle
                label: short title
                widget: string
              - name: description
                label: description
                widget: markdown
              - name: image
                label: image
                widget: image
          - name: ctaTitle
            label: cta title
            widget: string
          - name: ctaSubtitle
            label: cta subtitle
            widget: markdown
          - name: ctaActionTxt
            label: cta action txt
            widget: string
          - name: ctaActionLink
            label: cta action link
            widget: string
      - file: ./src/data/contact.md
        name: contact
        label: Contact
        fields:
          - name: splashImg
            label: splash img
            widget: image
          - name: title
            label: title
            widget: string
          - name: contactMethods
            label: contact methods
            widget: list
            fields:
              - name: type
                label: type
                widget: string
              - name: title
                label: title
                widget: string
              - name: info
                label: info
                widget: string
          - name: ctaTitle
            label: cta title
            widget: string
          - name: ctaSubtitle
            label: cta subtitle
            widget: markdown
          - name: ctaActionTxt
            label: cta action txt
            widget: string
          - name: ctaActionLink
            label: cta action link
            widget: string
          - name: directionsHeading
            label: directions heading
            widget: string
          - name: locations
            label: locations
            widget: list
            fields:
              - name: name
                label: name
                widget: string
              - name: directionsBody
                label: directions body
                widget: markdown
              - name: mapName
                label: map name
                widget: string
              - name: coordinates
                label: coordinates
                widget: object
                fields:
                  - name: lng
                    label: lng
                    widget: number
                  - name: lat
                    label: lat
                    widget: number
              - name: zoom
                label: zoom
                widget: number
          - name: faq
            label: faq
            widget: list
            fields:
              - name: q
                label: q
                widget: string
              - name: a
                label: a
                widget: string
          - name: aboutTitle
            label: about title
            widget: string
          - name: aboutContent
            label: about content
            widget: markdown
          - name: aboutImg
            label: about img
            widget: image
      - file: ./src/data/custom-flights.md
        name: custom-flights
        label: Custom Flights
        fields:
          - name: splashImg
            label: splash img
            widget: image
          - name: title
            label: title
            widget: string
          - name: description
            label: description
            widget: markdown
          - name: ctaTitle
            label: cta title
            widget: string
          - name: ctaSubtitle
            label: cta subtitle
            widget: string
          - name: ctaActionTxt
            label: cta action txt
            widget: string
          - name: ctaActionLink
            label: cta action link
            widget: string
      - file: ./src/data/global.md
        name: global
        label: Global
        fields:
          - name: subtitle
            label: subtitle
            widget: markdown
          - name: cta
            label: cta
            widget: string
          - name: video
            label: video
            widget: string
          - name: scrollPrompt
            label: scroll prompt
            widget: string
          - name: optionsTitle
            label: options title
            widget: string
          - name: optionsSubtitle
            label: options subtitle
            widget: markdown
          - name: scenicFlightsTitle
            label: scenic flights title
            widget: string
          - name: scenicFlightsSubtitle
            label: scenic flights subtitle
            widget: markdown
          - name: scenicFlightsAction
            label: scenic flights action
            widget: string
          - name: scenicFlightsActionLink
            label: scenic flights action link
            widget: string
          - name: scenicFlightsInfo
            label: scenic flights info
            widget: string
          - name: scenicFlightsInfoLink
            label: scenic flights info link
            widget: string
          - name: scenicFlightsImage
            label: scenic flights image
            widget: image
          - name: customTripsTitle
            label: custom trips title
            widget: string
          - name: customTripsSubtitle
            label: custom trips subtitle
            widget: markdown
          - name: customTripsAction
            label: custom trips action
            widget: string
          - name: customTripsActionLink
            label: custom trips action link
            widget: string
          - name: customTripsInfo
            label: custom trips info
            widget: string
          - name: customTripsInfoLink
            label: custom trips info link
            widget: string
          - name: customTripsImage
            label: custom trips image
            widget: image
          - name: commercialSolutionsTitle
            label: commercial solutions title
            widget: string
          - name: commercialSolutionsSubtitle
            label: commercial solutions subtitle
            widget: markdown
          - name: commercialSolutionsAction
            label: commercial solutions action
            widget: string
          - name: commercialSolutionsActionLink
            label: commercial solutions action link
            widget: string
          - name: commercialSolutionsInfo
            label: commercial solutions info
            widget: string
          - name: commercialSolutionsInfoLink
            label: commercial solutions info link
            widget: string
          - name: commercialSolutionsImage
            label: commercial solutions image
            widget: image
          - name: ourPartnersTitle
            label: our partners title
            widget: string
          - name: quoteText
            label: quote text
            widget: markdown
          - name: quoteAttr
            label: quote attr
            widget: string
          - name: quoteBg
            label: quote bg
            widget: image
          - name: partnersSections
            label: partners sections
            widget: list
            fields:
              - name: logos
                label: logos
                widget: list
                fields:
                  - name: image
                    label: image
                    widget: string
                  - name: name
                    label: name
                    widget: string
                  - name: url
                    label: url
                    widget: string
              - name: title
                label: title
                widget: string
          - name: raveReview
            label: rave review
            widget: string
          - name: reviewAttr
            label: review attr
            widget: string
          - name: actionBtn
            label: action btn
            widget: string
          - name: actionBtnLink
            label: action btn link
            widget: string
          - name: infoBtn
            label: info btn
            widget: string
          - name: infoBtnLink
            label: info btn link
            widget: string
          - name: footerImg
            label: footer img
            widget: image
      - file: ./src/data/scenic-flights.md
        name: scenic-flights
        label: Scenic Flights
        fields:
          - name: splashImg
            label: splash img
            widget: image
          - name: title
            label: title
            widget: string
          - name: description
            label: description
            widget: markdown
          - name: featurePages
            label: feature pages
            widget: list
            fields:
              - name: title
                label: title
                widget: string
              - name: description
                label: description
                widget: markdown
              - name: image
                label: image
                widget: image
          - name: ctaTitle
            label: cta title
            widget: string
          - name: ctaSubtitle
            label: cta subtitle
            widget: markdown
          - name: ctaActionTxt
            label: cta action txt
            widget: string
          - name: ctaActionLink
            label: cta action link
            widget: string
      - file: ./src/data/home.md
        name: home
        label: Home
        fields:
          - name: subtitle
            label: subtitle
            widget: markdown
          - name: cta
            label: cta
            widget: string
          - name: video
            label: video
            widget: string
          - name: scrollPrompt
            label: scroll prompt
            widget: string
          - name: optionsTitle
            label: options title
            widget: string
          - name: optionsSubtitle
            label: options subtitle
            widget: markdown
          - name: scenicFlightsTitle
            label: scenic flights title
            widget: string
          - name: scenicFlightsSubtitle
            label: scenic flights subtitle
            widget: markdown
          - name: scenicFlightsAction
            label: scenic flights action
            widget: string
          - name: scenicFlightsActionLink
            label: scenic flights action link
            widget: string
          - name: scenicFlightsImage
            label: scenic flights image
            widget: image
          - name: customTripsTitle
            label: custom trips title
            widget: string
          - name: customTripsSubtitle
            label: custom trips subtitle
            widget: markdown
          - name: customTripsAction
            label: custom trips action
            widget: string
          - name: customTripsActionLink
            label: custom trips action link
            widget: string
          - name: customTripsImage
            label: custom trips image
            widget: image
          - name: commercialSolutionsTitle
            label: commercial solutions title
            widget: string
          - name: commercialSolutionsSubtitle
            label: commercial solutions subtitle
            widget: markdown
          - name: commercialSolutionsAction
            label: commercial solutions action
            widget: string
          - name: commercialSolutionsActionLink
            label: commercial solutions action link
            widget: string
          - name: commercialSolutionsImage
            label: commercial solutions image
            widget: image
          - name: ourPartnersTitle
            label: our partners title
            widget: string
          - name: quoteText
            label: quote text
            widget: markdown
          - name: quoteAttr
            label: quote attr
            widget: string
          - name: quoteBg
            label: quote bg
            widget: image
          - name: partnersSections
            label: partners sections
            widget: list
            fields:
              - name: logos
                label: logos
                widget: list
                fields:
                  - name: image
                    label: image
                    widget: string
                  - name: name
                    label: name
                    widget: string
                  - name: url
                    label: url
                    widget: string
              - name: title
                label: title
                widget: string
          - name: raveReview
            label: rave review
            widget: string
          - name: reviewAttr
            label: review attr
            widget: string
          - name: actionBtn
            label: action btn
            widget: string
          - name: actionBtnLink
            label: action btn link
            widget: string
          - name: infoBtn
            label: info btn
            widget: string
          - name: infoBtnLink
            label: info btn link
            widget: string
          - name: footerImg
            label: footer img
            widget: image
